### PR TITLE
Bump deps and CI setup

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by nschonni** [comment]
@LaurentGoderre I think this was the only other one using the tagged version of `node-git-simple`

**Comment by LaurentGoderre** [comment]
Instead, can we get it to build for both versions of node?

**Comment by LaurentGoderre** [comment]
I don't remember what PR it was that we discussed the cache but will the cache be automatically invalidated when the package.json changes or do we manually have to do it each time?

**Comment by nschonni** [comment]
Caching looks for a cache that matches BRANCH.PLATFORM, and falls back to master.PLATFORM afterwards. NPM install is still run so anything that gets touched by that is updated.

You're right that this is a CLI tool, so I'll restore the 0.10, and add 0.12 and iojs too.

**Comment by nschonni** [comment]
I expanded the build testing to the current Node production releases

**Pull request merged**
